# Generated by Django 4.0.3 on 2022-08-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Men', 'Men'), ('Women', 'Women'), ('Home', 'Home'), ('Groceries', 'Groceries'), ('Kids', 'Kids')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='<django.db.models.fields.CharField>')),
            ],
        ),
    ]
