# Generated by Django 4.0.3 on 2022-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddGrocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='Grocery')),
            ],
        ),
        migrations.CreateModel(
            name='AddHomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='Home')),
            ],
        ),
        migrations.CreateModel(
            name='AddKidsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='Kids')),
            ],
        ),
        migrations.CreateModel(
            name='AddLaptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='Laptop')),
            ],
        ),
        migrations.CreateModel(
            name='AddMenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='Men')),
            ],
        ),
        migrations.CreateModel(
            name='AddMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='Mobile')),
            ],
        ),
        migrations.CreateModel(
            name='AddWomenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='Women')),
            ],
        ),
        migrations.DeleteModel(
            name='AddItem',
        ),
    ]
