# Generated by Django 4.0.3 on 2022-08-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_items_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='User',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
