# Generated by Django 4.0.3 on 2022-08-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
