# Generated by Django 4.0.3 on 2022-08-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_customer_profile_pic_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='cart'),
        ),
    ]
