# Generated by Django 4.0.3 on 2022-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cart_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item_image',
            field=models.ImageField(upload_to='cart'),
        ),
    ]
