# Generated by Django 4.0.3 on 2022-08-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_cart_item_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
