# Generated by Django 4.0.3 on 2022-08-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='cart',
            name='item_price',
            field=models.IntegerField(),
        ),
    ]
