# Generated by Django 4.0.3 on 2022-08-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_user_history_user_alter_cart_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addfootwear',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addgrocery',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addhomeitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addkidsitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addlaptop',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addmenitem',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addmobile',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addwatche',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addwomenitem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
